[build]
  command = "expo export"
  publish = "dist/web"
  
[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npx expo start --web"
  port = 19006
  targetPort = 19006
  framework = "expo"
